package:
  name: edipack
  version: "2.0.1"

source:
  git_url: https://github.com/EDIpack/EDIpack2.0.git

requirements:
  build:
    - pkg-config
    - cmake
    - make
    - ninja
    - meson
    - meson-python 
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi
    - libgfortran-ng=13  # [linux]
    - mpi
  host:
    - python
    - meson-python 
    - pip
    - numpy
    - mpi4py
    - mkl <2025 # [linux]
    - mkl-devel <2025  # [linux]
    - mkl-include <2025 # [linux]
    - openblas  # [osx]
    - lapack  # [osx]
    - scalapack  # [osx]
  run:
    - python
    - numpy
    - mpi4py
    - openmpi
    - mkl <2025 # [linux]
    - openblas  # [osx]
    - lapack  # [osx]
    - scalapack  # [osx]

about:
  home: https://github.com/EDIpack/EDIpack2.0
  license: MIT
  summary: "EDIpack - test"
  description: |
    This is a test.
  dev_url: https://github.com/EDIpack/EDIpack2.0

