name: Test get tag

on:
  workflow_dispatch: # This makes the workflow run only when manually triggered

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.13"]
    env:
      ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Latest Tag from edipack2.0
        run: |
          API_RESPONSE=$(curl -s  -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/edipack/edipack2.0/git/refs/tags")
          # Print the response for debugging
          echo "API Response: $API_RESPONSE"
          LATEST_TAG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/edipack/edipack2.0/git/refs/tags" | \
            jq -r '.[].ref' | sed 's#refs/tags/##g' | sort -V | grep -E '^[0-9]+(\.[0-9]+)*$' | tail -n 1)

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"

      - name: Create and activate build environment
        run: |
          conda create -n build-env python=${{ matrix.python-version }} rattler-build -y
          echo "CONDA_ENV=build-env" >> $GITHUB_ENV
          echo "Latest Tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

