name: test get tag

# This triggers on any creation event of a tag
on:
  create:
    tags:
      - '*'  # Matches any tag
  workflow_dispatch:

jobs:
  trigger-repo-c:
    runs-on: macos-latest
    steps:
      - name: 
        run: |
          LATEST_TAG=$(curl -s "https://api.github.com/repos/edipack/edipack2.0/git/refs/tags" | \
          jq -r '.[].ref' | sed 's#refs/tags/##' | sort -V | grep -v v | tail -n 1)
          echo "Latest Tag: \"$LATEST_TAG\""

