name: Test on mac os

on:
  workflow_dispatch: # This makes the workflow run only when manually triggered

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.12","3.13"]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"

      - name: Create and activate build environment
        run: |
          conda create -n testenv "python=3.12"
          conda init bash
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            source ~/.bash_profile
          else
            source ~/.bashrc
          fi
          conda activate testenv
          conda install -c conda-forge -c edipack edipack2
          cd test
          python3 hm_bethe.py

